facebook: "https://facebook.com/example"
twitter: "https://twitter.com/example"
email: "contact@example.org"
name: "Wonder Shapes"
location: Londonium
phone: (999) 999-9999
hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
