color = "#DC2626"
copyright = "Copyright &copy; 2024 Example Site. All Rights Reserved."
style = "blue"
logo = "/image/logo.png"
logo_small = "/image/logo.png"
about_us = """
Example Site is the world's leading manufacturer  of surgical supplies.
"""

[[footer]]
title = "About"
content = """
Example Site is the world's leading  manufacturer of surgical supplies.
"""

[[footer]]
title = "Recent Blog Posts"
recents = "blog"
recentCount = 7

[[footer]]
title = "Contact Us"
contact = true

[recent_posts]
enable = true
